name: app_leia_mais
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  flutter_mobx: ^1.1.0+2
  get_it: ^5.0.4
  mobx: ^1.2.1+4
  smooth_star_rating: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  mobx_codegen: ^1.1.2

flutter:

  uses-material-design: true
